

@startuml mdd

' skinparam linetype ortho
' skinparam linetype ortho
skinparam dpi 200


object Menu {
    titolo: testo
    pubblicato: sì/no

    consigliato cuoco: sì/no
    piatti caldi: sì/no
    richiede cucina: sì/no
    buffet: sì/no
    finger food: sì/no
}
object Sezione {
    nome: testo
}
object Voce {
    descrizione: testo
}
object Evento {
    titolo: testo
    note: testo
    penale: sì/no
    annullato: sì/no
    terminato: sì/no
    in corso: sì/no
}
object Chef {
    nome: testo
}
object Cuoco
object Membro_del_Personale
object Foglio_Riepilogativo
object Ricetta {
    titolo: testo
    pubblicato: si/no
    ingredienti: testo
    dosi: numero
}
object Scheda {
    data: data
    luogo: testo
    numero partecipanti: numero
}
object Preparazione{
    nome: testo
}
object Procedura_in_cucina
object Turno
object Tabellone_dei_turni
object Tag {
    nome: testo
}
object Ricettario
object Compito {
    porzioni / quantità: numero
    tempo stimato: numero
    porzioni già preparate: numero
}
object Passo {
    dettaglio
}




Procedura_in_cucina <|-- Ricetta
Procedura_in_cucina <|-- Preparazione
Membro_del_Personale <|-- Cuoco
Membro_del_Personale <|-- Chef
Menu "1" -- "0...n" Sezione : contiene >
Menu "01" -- "0n" Evento : è in uso in >
Chef "0n" -- "1" Menu : è creatore di >
Voce "0n" -- "01" Menu : appartiene direttamente > 
Voce "0n" -- "01" Sezione : si trova in >
Voce "0n" -- "1" Ricetta : fa riferimento a >
Foglio_Riepilogativo "01" -- "1" Evento : si riferisce a >
Scheda "1" -- "1" Evento : è associata a >
Membro_del_Personale "0...n" -- "0...n" Turno : lavora in >
Tabellone_dei_turni  "1" -- "0n" Turno: prevede >
Preparazione  "0n" -- "0n" Procedura_in_cucina : è ingrediente in >
Procedura_in_cucina  "0n" -- "0n"  Tag : classificata da >
Procedura_in_cucina  "0n" -- "1" Ricettario : si trova in >
Compito "0n" -- "1" Procedura_in_cucina : consiste in >
Foglio_Riepilogativo "1" -- "0n" Compito : richiede >
Compito "0n" -- "01" Cuoco : svolto da >
Compito "0n" -- "01" Turno : svolto in >
Membro_del_Personale "0n" -- "0n" Turno : disponibile in >

@enduml