@startuml

skinparam Dpi 400 dcd-eventi



Class Event {
    owner: Manager
    fine: boolean
    cancelled: boolean
    notes: List<String>
    form: Form
    chef: Chef
    staff: list<StaffMember>
    setChef(chef: Chef)
    setOwner(manager: Manager)
    setFine(fine: Boolean)
    setCancelled(cancelled: Boolean)
    createNotes()
    addNote(text: String)
    cancelEvent()
}

Interface EventEvReceiver{
    notifyEventCreated(e: Event)
    notifyEventSelected(e: Event)
    notifyStaffRemoved(e: Event s: List<StaffMember>)
    notifyEventCancelled(e: Event)
    notifyInfoModified(e: Event)
    notifyFormCreated(e: Event, f: Form)
    notifyChefAdded(e: Event, c: Chef)
    notifyStaffAdded(e: Event, s: List<Staff>)
    notifyNotesWritten(e: Event)
}

Class EventManager {
    currentEvent: Event
    createEvent(owner: Manager)
    setCurrentEvent(e: Event)
    selectEvent()
    getStaffList(): list<StaffMember>
    removeStaff()
    removeEvent()
    modifyInfo()
    getEvent(): Event
    createForm()
    setForm(form: Form)
    addChef()
    addStaff()
    writeNote()
}


Class Form {
    date: Data
    location: String
    n_participants: Number
    Form()
    setDate(date: Data)
    setLocation(place: String)
    setParticipants(n_part: Number)
    modifyForm()
}


Class Chef {
    isAvailable(): boolean
}
    
Class StaffMember {
    isAvailable(): Boolean
}

Class StaffManager {
    selectChef(): Chef
    selectStaffMember(staff_list: list<StaffMember>): StaffMember
}

EventEvReceiver "0..n" <-- EventManager

User "1" -- "0.n" Event
Event "1" -- "0..n" EventManager
User -- "0..n" UserManager
Form "1" -- "1" Event
StaffMember -- "0..n" StaffManager
Chef -- "0..n" StaffManager
Chef "1" -- "0..n" Event
StaffMember "0..n" -- "1..n" Event

@enduml
